FROM node:20
WORKDIR /app

ARG NPM_TOKEN

COPY server/.npmrc server/package.json server/package-lock.json ./
RUN npm ci

ENV MONGOMS_DOWNLOAD_DIR=/app/node_modules/.cache/mongodb-memory-server
RUN node -e "require('mongodb-memory-server').MongoMemoryServer.create().then(s=>s.stop()).then(()=>process.exit(0)).catch(e=>{console.error(e);process.exit(1)})"

COPY server/src ./src
COPY server/tsconfig.json server/jest.config.cjs server/jest.setup.cjs ./

RUN npm test -- --passWithNoTests
