FROM node:20
WORKDIR /app

ARG NPM_TOKEN

COPY .npmrc package*.json ./
COPY server/package.json ./server/
COPY client/package.json ./client/

RUN npm ci --workspace=server
RUN ls /app/node_modules/@nr/ && cat /app/node_modules/@nr/auth-middleware/package.json | grep '"version"' || echo "@nr/auth-middleware NOT FOUND"

ENV MONGOMS_DOWNLOAD_DIR=/app/server/node_modules/.cache/mongodb-memory-server
RUN cd server && node -e "require('mongodb-memory-server').MongoMemoryServer.create().then(s=>s.stop()).then(()=>process.exit(0)).catch(e=>{console.error(e);process.exit(1)})"

COPY server/ ./server/

RUN npm test -w server -- --passWithNoTests
